from enum import Enum


class GameStates(Enum):
    PLAYERS_TURN = 1
    ENEMY_TURN = 2
    PLAYER_DEAD = 3
    SHOW_INVENTORY = 4
    DROP_INVENTORY = 5
    TARGETING = 6
    LEVEL_UP = 7
    CHARACTER_SCREEN = 8
    EQUIPMENT_MENU = 9
    KEYBINDINGS_MENU = 10
    ESCAPE_MENU = 11
    HELP_SCREEN = 12
    OPTIONS_MENU = 13
    DEV_CONSOLE = 14
    LOOK = 15
